//
//  GameCampain.swift
//  Dragon Dreamers
//
//  Created by Kevin Ribeiro on 10/09/20.
//  Copyright © 2020 Kelvin Javorski Soares. All rights reserved.
//

import Foundation

class GameCampaign {
    
    var enemys: [Enemy] = [
        Enemy(name: "Vó Matilda",discussion:
            Discussion(
                agree: ["O Templo faz um trabalho excelente aqui na nossa cidade, eu mal posso esperar pra te mostrar tudo o que fazemos","Nós temos muito prestígio dentro da comunidade, e nos esforçamos muito para ajudar a todos que nos buscam","Todos os dias eu escuto agradecimento das pessoas da nossa comunidade pelo bem que o Templo fez por elas","Eu comecei a cuidar do tempo desde meus tempos de criança, quando a minha própria vó me passou os ensinamentos. Quem sabe um dia você ocupe o meu lugar.","Receber as pessoas todos os dias, conversar com elas, conhecer suas alegrias e seus sofrimentos. Poder guiá-los de acordo com nossas tradições é uma imensa alegria para mim.","Todas as pessoas dessa cidade tem as suas vidas conectadas ao Templo, todas elas já passaram buscando conselhos, e eu posso afirmar que cada uma delas já ouviu um conselho meu.","Eu digo sem sombra de dúvidas, o Templo é a minha maior conquista em vida, e representa tudo o que eu me dediquei e tudo o que eu fiz.","É bom ter alguém com quem compartilhar minhas experiências. Fico feliz que você esteja aqui para conversar comigo.","Eu espero que você se interesse pelas tradições de nossa cidade tanto quanto eu me interesso.","Um dia, se você desejar, eu posso te mentorar para que você entre no meu lugar como líder do Templo da cidade."],
                avoid: ["Como foi o passeio na cidade? Gostou de visitar o Templo?","Fico feliz que você fez novos amigos, algum deles frequenta o Templo? Talvez eu conheça eles também. Muitos dos jovens da cidade frequentam o Templo.","Você tem razão, está quase na hora do jantar. Podemos preparar algo para comer enquanto falamos de como foi seu dia.","Ah, você comprou tudo isso na loja do Lanre? Ele é um ávido participante das atividades do Templo e um amigo querido meu. Fico feliz que você conheceu ele. Ele comentou algo sobre o Templo?","Você conversou com Idara também? Eu adoro conversar com a família dela. É uma boa garota.","A cidade toda é adorável. As comidas, a arquitetura, a praia. Minha área favorita da cidade é o Templo que eu cuido. Fico feliz que tenha gostado do passeio.","Você aproveitou a praia? A água aqui é bem limpa, e os dias andam tão bonitos. Qualquer hora eu te acompanho em um passeio.","Fico feliz que você tenha entendido a filosofia do nosso povo. Os Caminhos da Brisa, do Oceano, da Areia e do Sol.","Eu espero que o tempo que você passou aqui te dê uma nova visão do mundo.","Venha mais vezes me visitar! Eu adoro a sua companhia!"],
                questioning: ["Não é fácil mudar as coisas, e há certas coisas que não sei se podem ser mudadas","Como convencer as pessoas a mudar a maneira de ver o mundo? O Templo mostra o caminho, mas não obriga ninguém a seguí-lo","Eu enxergo o Templo como um farol. Mesmo que mudássemos o farol de lugar, ou que trocássemos sua lente, isso não mudaria as pedras no caminho dos navios e barcos.","Em toda comunidade haverá conflitos entre gerações, e destes conflitos podem surgir problemas com as tradições, mas mudar as tradições não garante que esses conflitos deixarão de existir","Talvez seja necessário rever os impactos que o Templo tem em nossa comunidade, o que o Templo faz para a comunidade e o que a comunidade precisa do Templo","O Templo pode intervir em defesa de pessoas que se sintam excluídas da nossa comunidade, talvez possa trabalhar para estabelecer um diálogo","Por muito tempo eu dirigi o Templo focando nas tradições e crenças de nossa comunidade. Com o que você me diz, parece que eu perdi a conexão com a nossa própria comunidade e me foquei muito nas tradições.","Se nos prendermos muito as nossas tradições antigas, perdemos nossa conexão com as novas pessoas da nossa comunidade. Talvez seja tempo de refletirmos.","Mudanças são necessárias para que o Templo se mantenha relevante e conectado com a comunidade.","Para o Templo poder guiar a comunidade, o Templo precisa entender o que aflinge a comunidade. Você me fez um favor em me ajudar a ver isso."],
                criticize: ["Talvez quando você chegar na minha idade você veja as coisas de maneira diferente","Tradições são a maneira que as gerações anteriores e as novas tem de se comunicar, você não pode simplesmente largá-las","Você não pode forçar as pessoas a largarem a maneira como elas enxergam o mundo e lidam com as coisas, algumas pessoas simplesmente nunca mudam","Nem todas as mudanças são boas, se nós não tivermos nossas tradições para nos lembrarmos das coisas importantes da vida nós estaremos perdidos","Mesmo que o templo aceite as mudanças que você fala, o que garante que as pessoas aceitariam? Isso poderia levar o templo a descrédito, e outro mais tradicionalista ocuparia o lugar","As pessoas confiam no templo porque sabem o que ele defende. Mudar as coisas fará com que as pessoas percam a confiança em nós.","Nem todos se beneficiam das tradições, isso é verdade, mas infelizmente é assim que o mundo funciona. Algumas pessoas simplesmente não se encaixam com a sociedade, não há nada que se possa fazer.","Não é a intenção do templo excluir as pessoas que não seguem suas tradições, mas acaba sendo inevitável. Como conversar com alguém que vai contra o que você acredita?","E se ao invés de mudar o templo todo, por que você não fala para pessoa se integrar com as crenças?","O templo pode tentar mudar, mas nada garante que as pessoas mudarão também"],
                humorPoits: 5))]
    
    init() {
        
    }
    
}
